name: 'Auto-assign Reviewer'
description: 'Auto-assigns reviewers to teams users'
inputs:
    repo-token:
        description: 'The GITHUB_TOKEN needed to update the issue'
        default: ${{ github.token }}
    targetTeam:
        description: 'The name of the team to which the target assignees belong'
        required: true
    excludeAssignees:
        description: 'Users to be excluded from being assigned as reviewers (comma-separated)'
        required: false
    numOfAssignee:
        description: 'Number of random assignees'
        required: true
    issueNumber:
        description: 'Manually specified issue (or PR) ID to be used instead of the one in the context'
        required: false

runs:
    using: 'node20'
    main: 'src/index.js'

branding:
    icon: 'alert-circle'
    color: 'red'
